services:
  gateway.webapi:
    image: ${DOCKER_REGISTRY-}gatewaywebapi
    build:
      context: .
      dockerfile: src/Gateway/Gateway.WebApi/Dockerfile
  user.webapi:
    image: ${DOCKER_REGISTRY-}userwebapi
    build:
      context: .
      dockerfile: src/Services/User/User.WebApi/Dockerfile
