services:
  gateway.webapi:
    image: ${DOCKER_REGISTRY-}gatewaywebapi
    build:
      context: .
      dockerfile: src/Gateway/Gateway.WebApi/Dockerfile
  user.webapi:
    image: ${DOCKER_REGISTRY-}userwebapi
    build:
      context: .
      dockerfile: src/Services/User/User.WebApi/Dockerfile
  db:
    image: postgres:18.3
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - server
  redis:
    image: redis:alpine
    networks:
      - server

networks:
  server:

volumes:
  db_data: