services:
  gateway.webapi:
    image: ${DOCKER_REGISTRY-}gatewaywebapi
    build:
      context: .
      dockerfile: Gateway.WebApi/Dockerfile
  user.webapi:
    image: ${DOCKER_REGISTRY-}userwebapi
    build:
      context: .
      dockerfile: User.WebApi/Dockerfile
